### ISSUE TITLE
xl browser size

### ISSUE THREAD

**Issue by stillfire** [AnalogJ/matchmedia-ng#15]
Is there a way to add a variable for an xl browser size without editing the match-media.js file directly?

eg.

var defaultRules = {
xl : '(min-width: 1600px)',
lg : '(min-width: 1200px) and (max-width:1599px)',
md : '(min-width: 992px) and (max-width: 1199px)',
sm : '(min-width: 768px) and (max-width: 991px)',
xs : '(max-width: 767px)'
};

**Comment by AnalogJ** [comment]
Unfortunately theres no way to specify additional aliases, like `isXL` or `isLG`, however you can override the default rules for existing aliases such as `tablet`, `portrait`, `landscape`, check that out here: https://github.com/AnalogJ/matchmedia-ng/blob/master/matchmedia-ng.js#L27-L37

If you need to test for a custom alias that doesn't exist you can do that using `is()` and `on()` https://github.com/AnalogJ/matchmedia-ng#custom-media-queries

Hopefully that's what you needed.
