### ISSUE TITLE
.on function trigerred at wrong time

### ISSUE THREAD

**Issue by georgeslegros** [AnalogJ/matchmedia-ng#23]
Hi there,

I just tried to play a bit with the lib and here is my setup:

In app.config I added the following custom rules:
```
matchmediaProvider.rules.phone = "(max-width: 799px)";
matchmediaProvider.rules.desktop = "(min-width: 800px)";
```

Then in my directive controller I have this:
```
                    matchmedia.onPhone(function() {
                            console.log("PHONE");
                        });

                    matchmedia.onDesktop(function() {
                            console.log("DESKTOP");
                        });
```

Result is that I get both PHONE and DESKTOP in the console at each transition between the states, meaning when I go under 800px and when I go above it. I expected to get PHONE when going under and DESKTOP when going above.
For the record, I also tried with the .on function and passing the "max-..." param and I get the same result.

There is no exception raised or errors in the console and setting the dev mode did not really gave much info besides:
["Creating matchmedia"] 
["adding listener for query: (max-width: 799px)"]
["adding listener for query: (min-width: 800px)"]

I am using it wrong?

Thanks,

**Comment by georgeslegros** [comment]
That was actually me being stupid, I need to use the matches...

**Comment by AnalogJ** [comment]
😃  Im glad you got it all figured out. I'm open to a PR's to clarify anything confusing in the Readme.
