### ISSUE TITLE
IE9 TypeError: Object doesn't support property or method 'addListener' 

### ISSUE THREAD

**Issue by owlyowl** [AnalogJ/matchmedia-ng#7]
Line 68 where mediaQueryList.addListener(handler) is still blowing up even if you include the matchmedia polyfill from Paul Irish

**Comment by stranger-tepa** [comment]
This is an old post, but I thought about posting any way. I am also getting the same error when navigating to Angular Material home page using IE 9. The page is not being rendered as expected.

URL: https://material.angularjs.org/latest/#/

This is what is being logged on the console:
TypeError: Object doesn't support property or method 'matchMedia'

**Comment by AnalogJ** [comment]
Hey @stranger-tepa which version of matchmedia-ng are you using?

**Comment by AnalogJ** [comment]
closing.
